name: Continuous Integration

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run lint
        run: |
          npm lint
      - name: Run tests
        run: |
          npm test
